name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt 

      - name: Set Up Test Environment
        run: echo "DATABASE=test_feedback.db" > .env  # Creates .env inside CI

      - name: Run Tests
        run: python -m pytest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Only run if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Deployment to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-cvlskradbo4c7387sij0",
              "branch": "master"
            }' \
            https://api.render.com/v1/services/srv-cvlskradbo4c7387sij0/deploys

